### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by tianlinzx** [xuanye/plantuml-style-c4#1]
https://www.cnblogs.com/xuanye/p/new-style-4-plantuml-and-c4model.html

Several examples in this article cant' be rendered both from the article url or run in local environment.

**Comment by tianlinzx** [comment]
c4-container-sample.puml
c4-component-sample.puml

**Comment by xuanye** [comment]
Online service conversion failed, but local conversion was successful and the image in the readme file has been replaced

**Comment by xuanye** [comment]
https://www.planttext.com/
don‘t support definedlong?

**Comment by tianlinzx** [comment]
Maybe I am on Mac, and many other encountered the same issue.
Refer to https://github.com/RicardoNiepel/C4-PlantUML/issues/23

**Comment by tianlinzx** [comment]
Anyway , I have resolved the problem by chaning definedlong to function
