### ISSUE TITLE
Missing / bad styling for "groups"

### ISSUE THREAD

**Issue by haakoo** [xuanye/plantuml-style-c4#4]
While creating a sequence diagram today I needed to use [PlantUML groups](http://plantuml.com/sequence-diagram) (search for `Grouping message`). The result is less than optimal. Black(?) text on dark grey makes it very hard to read.

The following code show the problem.

```plantuml
@startuml
!includeurl https://raw.githubusercontent.com/xuanye/plantuml-style-c4/master/core.puml
' uncomment the following line and comment the first to use locally
'!include core.puml

Alice -> Bob: Authentication Request

alt successful case

	Bob -> Alice: Authentication Accepted
	
else some kind of failure

	Bob -> Alice: Authentication Failure
	group My own label
		Alice -> Log : Log attack start
	    loop 1000 times
	        Alice -> Bob: DNS Attack
	    end
		Alice -> Log : Log attack end
	end
	
else Another type of failure

   Bob -> Alice: Please repeat
   
end
@enduml
```

![Sequence diagram groupings](http://www.plantuml.com/plantuml/png/XP51ZzD038NFcL_nEEsfJP4uzO0s2742XE0Nk1Et7QrZXncFIluzam2BAYJM1n_otlVYftaiJjdh9E5LqYXrv9e5L_Uv7Fi-qsr_INwjfreuHrDdzNsqgVzHIHVkPo5TwLtnHNWNt_GJ5UVSHykydzVS1rHjnDH8-9LnDX6x9Rr0aZ98Hzp9AHU76sfXY4KIMSB3d-FmDpSCaY9ZznRlx7J4K1kjdY9vCiLN_bwvU0WaZb9Zv5BELH2fS0XTGrPoY_Y77PfxTXv35rWAezZ4U4ewmiuuKvAQNypuyDlMNRBL6PyMs4qXT689NVTy-aUxuBXjSgVuXEqvGeSsOZRZzU5mWAU9o_Pnc_lYxpz_mx31lnoiut__iEcip-q6DRzoXYyptnK4S5_nYp0r8FFCvAiSrfZ7jkeaFm40)

I might have a look at this later, and change the colours to improve readability. Or are you already aware of this?

**Comment by xuanye** [comment]
![微信截图_20190809104800](https://user-images.githubusercontent.com/756204/62750618-5d501900-ba93-11e9-9882-c51ae7e66715.png)

changed color

**Comment by xuanye** [comment]
![微信截图_20190809104800](https://user-images.githubusercontent.com/756204/62750618-5d501900-ba93-11e9-9882-c51ae7e66715.png)

changed color

**Comment by haakoo** [comment]
It looks good, thank you.
