### ISSUE TITLE
LAYOUT_WITH_LEGEND Syntax Error

### ISSUE THREAD

**Issue by fhchina** [xuanye/plantuml-style-c4#9]

**Comment by luzhengyu1990** [comment]
met the same error, the hint gives LAYOUT_WITH_LEGEND, why is that?

**Comment by xuanye** [comment]
plantuml last version didn‘t support  `definelong`

**Comment by missley** [comment]
能不能帮忙解决下这个问题，这个插件对我们来说很重要，谢谢！

**Comment by xuanye** [comment]
> 能不能帮忙解决下这个问题，这个插件对我们来说很重要，谢谢！

你更新到plantuml最新版本，我master分支中的代码已经替换了相关的语法
